language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=https://github.com/django/django/archive/1.5c1.zip
  - DJANGO=django==1.4.3

install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - python setup.py test
